version: "3.8"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    container_name: "db_mini_market"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mini_market_dev
    ports:
      - '5432:5432'
